#!/usr/bin/expect

set filename [lindex $argv 0]
set space "        "
set usage "Usage: fss \[-h\] config_file \[command\]\n    -h             show this help message\n    config_file    host, username, password, parameters\n    command        \(optional\) ssh \(by default\) / sftp"
if {$filename == ""} {
    puts $usage;
    exit
}
if {$filename == "-h"} {
    puts $usage;
    exit
}
set file [open $filename]
set data [split [read $file] "\n"]
close $file
set host [lindex $data 0]
set username [lindex $data 1]
set password [lindex $data 2]
set parameters [lindex $data 3]

set command [lindex $argv 1]
if {$command == ""} {
    puts "Using ssh by default.";
    set command "ssh";
}
spawn $command $username@$host $parameters
expect {
    "*?assword:" {
        send "$password\n"
        expect {
            "*?$username@*?" { interact }
            "sftp>" { interact }
        }
    }
    "*?(yes/no*?" {
        send "yes\n"
        expect "*?assword:"
        send "$password\n"
        expect {
            "*?$username@*?" { interact }
            "sftp>" { interact }
        }
    }
    "*?$username@*?" { interact }
    "sftp>" { interact }
}
